---

kind: pipeline
type: exec
name: deploy-prod

steps:
    - name: composer
      commands:
          - composer install
    - name: deploy to server
      environment:
          DEPLOY_COMMAND:
              from_secret: deploy_command_prod
      commands:
          - $${DEPLOY_COMMAND}

trigger:
    branch:
        - main
    event:
        - push

---

kind: pipeline
name: build-dev-container

steps:
    - name: docker
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo: keyoxide/keyoxide
          tags: dev

---

kind: pipeline
type: exec
name: deploy-dev

steps:
    - name: pull docker container
      commands:
          - docker pull keyoxide/keyoxide:dev
    - name: stop and remove existing docker container
      commands:
          - docker stop keyoxide-web
          - docker rm keyoxide-web
    - name: run new docker container
      environment:
          TWITTER_API_AUTH:
              from_secret: twitter_api_auth
      commands:
          - docker run -d -e "TWITTER_API_AUTH=$${TWITTER_API_AUTH}" --name keyoxide-web -h keyoxide --network dc_web keyoxide-web

depends_on:
    - build-dev-container

trigger:
    branch:
        - dev
    event:
        - push
