---

kind: pipeline
name: build-stable-container

steps:
    - name: build stable container
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo: keyoxide/keyoxide
          tags: stable
    - name: build tag container
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo: keyoxide/keyoxide
          auto_tag: true

trigger:
    event:
        - tag

---

kind: pipeline
name: build-dev-container

steps:
    - name: build dev container
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo: keyoxide/keyoxide
          tags: dev

trigger:
    branch:
        - main
    event:
        - push
